#jdbc:h2:tcp://localhost/~/jpashop
#username : sas
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_basic_shop
#    url: jdbc:mysql://127.0.0.1:3306/bookshop
#    username: root
#    password: 1234
    username: ba756112c0c481
    password: 34a20003
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        # show_sql: true
        format_sql: true
    show_sql : true
logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type: trace
    org.hibernate.type: trace